[project]
name = "cs02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "gradio[oauth]>=6.29.0",
    "huggingface-hub>=1.33.0",
    "pillow>=12.3.0",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "transformers>=5.18.0",
]

[tool.pyright]
extraPaths = ["."]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu", marker = "sys_platform == 'linux'" }]
torchvision = [{ index = "pytorch-cpu", marker = "sys_platform == 'linux'" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
